### ISSUE TITLE
Checklist for 1.0 release

### ISSUE THREAD

**Issue by dsblank** [ArtificialIntelligenceToolkit/aitk.robots#9]
- [x] robot's camera can see a bulb through a wall
- [x] smell sensors and light sensors both show up as small circles on the robot; makes it hard to distinguish between the two. Perhaps the smell sensors could be squares? 
- [x] As a robot equipped with a camera approaches food, when it is quite close to the food it becomes invisible (not showing up in the image). 
- [x] device constructors should raise exception when given an unknown parameter
- [x] single-line wall issues: don't block smell, don't save with config
- [x] watched views should have a blue border
- [x] need to test GroundCamera, pen_up() and pen_down()
- [x] draw light in world (top-down view) so that it hits walls rather than drawing under them
- [x] bring docs up to date
- [ ] Colab issues
    - [x] no-joystick button grid is overlapping
    - [ ] joystick control in colab
- [x] Recorder issues
    - [x] recording should use max_trace_length
    - [x] might be an issue with recorder.get_trace() to get a long trace
    - [x] smells/food and bulb on/off aren't integrated with recorder
    - [x] recorder doesn't play last step
- [ ] why does "Resetting seed" show an increasing number of times?
